services:
  - type: web
    name: logitrack-web
    env: dotnet
    plan: free
    region: singapore
    buildCommand: dotnet publish -c Release -o out
    startCommand: dotnet out/jamesmvc.dll
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production